#!/usr/bin/env python3
"""
Wifers App - FastAPI Backend Server

Provides REST API endpoints for:
  - /predict: AP status prediction (Up/Down) - v3 model (real available features)
  - /predict/signal_strength/heatmap: Pre-computed signal strength heatmap
  - /predict/signal_strength/ap_trend: Daily signal trend for a specific AP
  - /recommend: AP recommendation based on location and preferences
  - /route: Basic routing between two points
  - /route/advanced: Advanced routing with signal-aware pathfinding
  - /health: Health check endpoint
  - /status: Detailed server status
  - /cache/status: Cache statistics

Pre-computed heatmap files are served from precomputed/{day}/heatmap_h{hour}.json.
"""

import heapq
import json
import math
import os
import time
import uuid
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any, Optional

import uvicorn
from fastapi import FastAPI, File, HTTPException, Query, UploadFile
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator


BASE_DIR = Path(__file__).resolve().parent
MODELS_DIR = BASE_DIR / "models"
PRECOMPUTED_DIR = BASE_DIR / "precomputed"
TRENDS_DIR = PRECOMPUTED_DIR / "trends"
GEOJSON_PATH = BASE_DIR / "geolocation_package" / "data" / "aps_geolocalizados_wgs84.geojson"

DAY_NAMES = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
DAY_FULL_NAMES = {
    "monday": "mon", "tuesday": "tue", "wednesday": "wed",
    "thursday": "thu", "friday": "fri", "saturday": "sat", "sunday": "sun",
}
NIGHT_REPRESENTATIVE_HOUR = 3
TREND_FILE_TTL = 3600  # File cache TTL for trend results (seconds)

app = FastAPI(title="Wifers App API", description="Backend API for Wi-Fi signal prediction and recommendation", version="3.0.0")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

_decision_tree_v3: Any = None
_decision_tree_v3_meta: Optional[dict] = None
_building_encoder: Any = None
_ap_name_encoder: Any = None
_signal_strength_model: Any = None
_signal_strength_meta: Optional[dict] = None
_geojson_data: Optional[dict] = None
_ap_index: Optional[list[dict]] = None
_buildings_list: Optional[list[str]] = None
_ap_index_by_name: dict[str, dict] = {}

# --- Predictor5_0 (LSTM) global state ---
_predictor5_loaded: bool = False
_predictor5_model: Any = None
_predictor5_scaler: Any = None
_predictor5_le_ap: Any = None
_predictor5_meta: Optional[dict] = None
# AP hourly profile cache — average numeric features per hour for LSTM window construction
_predictor5_ap_profiles: Optional[dict] = None
_predictor5_window_cache: dict[int, dict] = {}  # {hash(ap_name+date): window_data}
PREDICTOR5_MODEL_DIR = str(BASE_DIR / "predictor5_model")

# Booking PERFORMANCE RANK — unified mapping for all models
PERF_RANK = {
    'Very Poor': 0, 'Weak': 1, 'Poor': 1, 'Fair': 2, 'Good': 3,
    'Excellent': 4, 'Excellent+': 5, 'Excellent++': 6
}
# LSTM signal_score → booking label threshold
LSTM_SCORE_THRESHOLDS = [
    (0.95, 'Excellent++'),
    (0.90, 'Excellent+'),
    (0.80, 'Excellent'),
    (0.70, 'Good'),
    (0.50, 'Fair'),
    (0.00, 'Poor'),  # Poor = Weak
]

# --- Lightweight route graph (precomputed JSON, no osmnx/networkx) ---
_LIGHT_ROUTE_GRAPH: Optional[dict] = None


def _load_light_route_graph() -> dict:
    """Load the precomputed lightweight route graph from JSON.

    This tiny file (~140 KB) was generated by running precompute_route_graph.py
    locally. Contains the UAB campus walking network as a simple node/edge list.
    No osmnx, no networkx — memory usage: < 1 MB (vs 100-200 MB before).
    """
    global _LIGHT_ROUTE_GRAPH
    if _LIGHT_ROUTE_GRAPH is not None:
        return _LIGHT_ROUTE_GRAPH

    light_path = MODELS_DIR / "route_graph_light.json"
    if not light_path.exists():
        raise FileNotFoundError(
            f"Route graph not found at {light_path}. "
            "Run precompute_route_graph.py on your development machine first."
        )

    with open(light_path) as f:
        _LIGHT_ROUTE_GRAPH = json.load(f)

    n_nodes = len(_LIGHT_ROUTE_GRAPH["nodes"])
    n_edges = len(_LIGHT_ROUTE_GRAPH["edges"])
    print(f"[INFO] Loaded light route graph: {n_nodes} nodes, {n_edges} edges ({light_path.stat().st_size / 1024:.1f} KB)")
    return _LIGHT_ROUTE_GRAPH


def _find_route_path(lat: float, lng: float, dest_lat: float, dest_lng: float, acceptable_range: int = 500) -> dict:
    """
    Find a walking path on the UAB campus road graph using pure Python Dijkstra.
    No osmnx, no networkx — just a JSON file and heapq (< 1 MB memory).
    """
    graph = _load_light_route_graph()
    nodes = graph["nodes"]
    edges = graph["edges"]

    # Build adjacency list
    adj: dict[str, list[tuple[str, float]]] = {}
    for u, v, length in edges:
        adj.setdefault(u, []).append((v, length))
        adj.setdefault(v, []).append((u, length))

    def nearest_node(lat: float, lng: float) -> str:
        best_id = None
        best_dist = float("inf")
        for nid, ndata in nodes.items():
            d = _haversine_distance(lat, lng, ndata["lat"], ndata["lng"])
            if d < best_dist:
                best_dist = d
                best_id = nid
        return best_id

    start_node = nearest_node(lat, lng)
    dest_node = nearest_node(dest_lat, dest_lng)

    if start_node is None or dest_node is None:
        return {"path": [], "distance": 0, "waypoints": [], "total_waypoints": 0}

    # Pure Python Dijkstra
    distances: dict[str, float] = {start_node: 0}
    prev: dict[str, str | None] = {start_node: None}
    pq: list[tuple[float, str]] = [(0, start_node)]

    while pq:
        d, u = heapq.heappop(pq)
        if u == dest_node:
            break
        if d > distances.get(u, float("inf")):
            continue
        for v, w in adj.get(u, []):
            nd = d + w
            if nd < distances.get(v, float("inf")):
                distances[v] = nd
                prev[v] = u
                heapq.heappush(pq, (nd, v))

    if dest_node not in distances or distances[dest_node] == float("inf"):
        return {"path": [], "distance": 0, "waypoints": [], "total_waypoints": 0}

    path_nodes: list[str] = []
    u: str | None = dest_node
    while u is not None:
        path_nodes.append(u)
        u = prev.get(u)
    path_nodes.reverse()

    path_coords = []
    for nid in path_nodes:
        nd = nodes[nid]
        path_coords.append({"lat": nd["lat"], "lng": nd["lng"]})

    # Find APs near start/dest as waypoints (same as before)
    ap_index = _build_ap_index()
    path_aps = []
    for ap in ap_index:
        dist_to_start = _approximate_distance(lat, lng, ap["lat"], ap["lng"])
        dist_to_dest = _approximate_distance(dest_lat, dest_lng, ap["lat"], ap["lng"])
        if dist_to_start <= acceptable_range or dist_to_dest <= acceptable_range:
            path_aps.append({
                "lat": ap["lat"], "lng": ap["lng"],
                "building": ap["building"], "floor": int(ap["floor"]),
                "ap_name": ap["name"],
                "distance_to_start": round(dist_to_start, 1),
                "distance_to_dest": round(dist_to_dest, 1),
            })

    return {
        "path": path_coords,
        "distance": round(distances[dest_node], 1),
        "waypoints": path_aps,
        "total_waypoints": len(path_aps),
    }


# --- Booking system (in-memory storage) ---
_bookings: list[dict] = []
_room_lookup: dict[str, dict] = {}

# --- Prediction feedback / accuracy tracking ---
_prediction_feedback: list[dict] = []  # Stores {ap_name, hour, predicted, actual, timestamp}

# --- Actual signal data from clientes_processed.csv for accuracy comparison ---
_actual_signal_data: dict[str, dict] = {}  # {ap_name_lower: {hourly: {hour: {actual_mean, samples}}, total_measurements}}
_actual_signal_loaded: bool = False

def _load_actual_signal_data(force_reload: bool = False):
    """Load precomputed actual signal averages from JSON (not CSV).
    
    Args:
        force_reload: If True, reload from disk even if already loaded.
                      Useful on file changes.
    """
    global _actual_signal_data, _actual_signal_loaded
    if _actual_signal_loaded and not force_reload:
        return _actual_signal_data
    
    json_path = BASE_DIR / "precomputed" / "actual_signal_averages.json"
    if not json_path.exists():
        print(f"[WARN] Precomputed actual signal averages not found: {json_path}")
        _actual_signal_loaded = True  # Don't keep retrying for missing file
        return _actual_signal_data
    
    try:
        print(f"[INFO] Loading precomputed actual signal averages from {json_path}...")
        with open(json_path) as f:
            raw = json.load(f)
        
        # Convert string hour keys back to int for consistency
        for ap_key, ap_data in raw.items():
            hourly = ap_data.get("hourly", {})
            converted_hourly = {}
            for h_str, h_data in hourly.items():
                converted_hourly[int(h_str)] = h_data
            _actual_signal_data[ap_key] = {
                "hourly": converted_hourly,
                "total_measurements": ap_data["total_measurements"],
            }
        
        print(f"[INFO] Loaded actual signal averages for {len(_actual_signal_data)} APs")
        _actual_signal_loaded = True
    except Exception as e:
        print(f"[ERROR] Failed to load actual signal averages: {e}")
        # Don't set _actual_signal_loaded = True on error so we retry next time
        # Reset in case of partial load
        _actual_signal_data = {}
    
    return _actual_signal_data




def _load_decision_tree_v3():
    import joblib
    global _decision_tree_v3, _decision_tree_v3_meta
    if _decision_tree_v3 is None:
        path = MODELS_DIR / "decision_tree_v3.joblib"
        if not path.exists():
            path = MODELS_DIR / "decision_tree.joblib"
            if not path.exists():
                raise FileNotFoundError("No decision tree model found")
        _decision_tree_v3 = joblib.load(path)
        meta_path = MODELS_DIR / "decision_tree_meta_v3.json"
        if meta_path.exists():
            with open(meta_path) as f:
                _decision_tree_v3_meta = json.load(f)
        else:
            _decision_tree_v3_meta = {}
    return _decision_tree_v3


def _load_building_encoder():
    import joblib
    global _building_encoder
    if _building_encoder is None:
        path = MODELS_DIR / "building_encoder.joblib"
        if path.exists():
            _building_encoder = joblib.load(path)
    return _building_encoder


def _load_ap_name_encoder():
    import joblib
    global _ap_name_encoder
    if _ap_name_encoder is None:
        path = MODELS_DIR / "ap_name_encoder.joblib"
        if path.exists():
            _ap_name_encoder = joblib.load(path)
    return _ap_name_encoder


def _encode_ap_name(ap_name: str) -> int:
    """Encode AP name using the label encoder. Returns 0 if not found."""
    encoder = _load_ap_name_encoder()
    if encoder is None:
        return 0
    # Try exact match first, then stripped
    clean_name = ap_name.strip()
    if clean_name in encoder.classes_:
        return int(encoder.transform([clean_name])[0])
    # Try with leading space (some encoder classes have leading spaces)
    if f" {clean_name}" in encoder.classes_:
        return int(encoder.transform([f" {clean_name}"])[0])
    # Try case-insensitive
    for cls in encoder.classes_:
        if cls.strip().lower() == clean_name.lower():
            return int(encoder.transform([cls])[0])
    return 0


# ─────────────────────────────────────────────
#  Predictor5_0 LSTM — 懒加载 + AP 轮廓缓存
# ─────────────────────────────────────────────

def _load_predictor5() -> bool:
    """Lazy-load Predictor5_0 LSTM model, scaler, label_encoder, meta.

    Returns True if loaded successfully, False otherwise.
    """
    global _predictor5_loaded, _predictor5_model, _predictor5_scaler
    global _predictor5_le_ap, _predictor5_meta

    if _predictor5_loaded:
        return True

    model_dir = Path(PREDICTOR5_MODEL_DIR)
    meta_path = model_dir / "meta.joblib"
    if not meta_path.exists():
        print("[WARN] Predictor5_0 meta not found — LSTM unavailable")
        return False

    try:
        import joblib, torch, torch.nn as nn
        import numpy as np

        _predictor5_meta = joblib.load(str(meta_path))
        _predictor5_scaler = joblib.load(str(model_dir / "scaler.joblib"))
        _predictor5_le_ap = joblib.load(str(model_dir / "label_encoder.joblib"))

        # Rebuild LSTM model
        lstm1 = _predictor5_meta.get('lstm_units_1', 80)
        lstm2 = _predictor5_meta.get('lstm_units_2', 48)
        dense_u = _predictor5_meta.get('dense_units', 32)
        n_feats = _predictor5_meta.get('n_features', 15)
        fh = _predictor5_meta['forecast_horizon']

        device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')

        # Define the same architecture as in run_predictor5.py
        class LSTMBookingPredictor(nn.Module):
            def __init__(self, input_size, hidden1, hidden2, dense_units, output_size):
                super().__init__()
                self.lstm1 = nn.LSTM(input_size, hidden1, batch_first=True)
                self.drop1 = nn.Dropout(0.25)
                self.lstm2 = nn.LSTM(hidden1, hidden2, batch_first=True)
                self.drop2 = nn.Dropout(0.25)
                self.fc1 = nn.Linear(hidden2, dense_units)
                self.relu = nn.ReLU()
                self.fc2 = nn.Linear(dense_units, output_size)

            def forward(self, x):
                x, _ = self.lstm1(x)
                x = self.drop1(x)
                x, _ = self.lstm2(x)
                x = self.drop2(x)
                x = x[:, -1, :]
                x = self.relu(self.fc1(x))
                x = self.fc2(x)
                return x

        _predictor5_model = LSTMBookingPredictor(n_feats, lstm1, lstm2, dense_u, fh)
        state = torch.load(str(model_dir / "model_state.pt"), map_location=device, weights_only=True)
        _predictor5_model.load_state_dict(state)
        _predictor5_model.to(device)
        _predictor5_model.eval()

        _predictor5_loaded = True
        print(f"[INFO] Predictor5_0 LSTM loaded ({_predictor5_meta['n_aps_used']} APs, "
              f"test_MAE={_predictor5_meta['test_mae']:.4f})")
        return True

    except Exception as e:
        print(f"[ERROR] Failed to load Predictor5_0: {e}")
        import traceback
        traceback.print_exc()
        _predictor5_meta = None
        return False


def _load_predictor5_ap_profiles() -> Optional[dict]:
    """Load precomputed AP hourly profiles for LSTM window construction.

    Returns dict: {ap_name: {day_of_week: {hour: {feat: val, ...}}}}
    """
    global _predictor5_ap_profiles
    if _predictor5_ap_profiles is not None:
        return _predictor5_ap_profiles

    profile_path = Path(str(BASE_DIR / "precomputed" / "predictor5_ap_profiles.json"))
    if not profile_path.exists():
        print("[WARN] Predictor5_0 AP profiles not found — run precompute_predictor5_profiles.py")
        return None

    try:
        import json
        with open(profile_path) as f:
            _predictor5_ap_profiles = json.load(f)
        print(f"[INFO] Predictor5_0 AP profiles loaded ({len(_predictor5_ap_profiles)} APs)")
        return _predictor5_ap_profiles
    except Exception as e:
        print(f"[ERROR] Failed to load Predictor5_0 profiles: {e}")
        return None


def _signal_score_to_label(score: float) -> str:
    """Convert a signal_score (0-1) to a booking performance label."""
    for threshold, label in LSTM_SCORE_THRESHOLDS:
        if score >= threshold:
            return label
    return 'Poor'


def _predict_lstm_for_booking(ap_name: str, date_str: str, start_hour: int, end_hour: int) -> Optional[dict]:
    """Use Predictor5_0 LSTM to predict signal_score for a booking slot.

    Returns dict with 'label', 'scores' (hourly dict), or None if LSTM unavailable.
    """
    if not _predictor5_loaded:
        if not _load_predictor5():
            return None

    ap_profiles = _load_predictor5_ap_profiles()
    if ap_profiles is None:
        return None

    ap_key = ap_name.strip().lower()
    # Find matching AP in profiles (case-insensitive, fuzzy)
    matched_key = None
    for profile_key in ap_profiles:
        if profile_key.strip().lower() == ap_key:
            matched_key = profile_key
            break
    if matched_key is None:
        return None

    ap_code = None
    if _predictor5_le_ap is not None:
        try:
            clean = ap_name.strip()
            if clean in _predictor5_le_ap.classes_:
                ap_code = int(_predictor5_le_ap.transform([clean])[0])
            else:
                for cls in _predictor5_le_ap.classes_:
                    if cls.strip().lower() == ap_key:
                        ap_code = int(_predictor5_le_ap.transform([cls])[0])
                        break
        except Exception:
            pass
    if ap_code is None:
        return None

    import numpy as np
    import torch

    W = _predictor5_meta['window_size']  # 24
    FH = _predictor5_meta['forecast_horizon']  # 12
    all_feats = _predictor5_meta['all_features']
    target_idx = _predictor5_meta['target_idx']
    numeric_feats = _predictor5_meta['numeric_features']

    booking_dt_obj = __import__('datetime').datetime.strptime(date_str, "%Y-%m-%d")
    dow = booking_dt_obj.weekday()  # 0=Mon

    # Build 24h window: timestamps [start_hour-24 .. start_hour-1]
    feat_rows = []
    for offset in range(W):
        ts_hour = (start_hour - W + offset) % 24
        ts_dow = dow
        # Handle day boundary: if ts_hour wraps, adjust dow
        hour_delta = start_hour - (W - offset)
        actual_dow = (dow - 1) if hour_delta < 0 else dow
        # Actually simpler: compute absolute hour offset
        # Hour 0 of window = start_hour - 24 hours
        # Each step = start_hour - 24 + offset
        abs_hour = start_hour - W + offset
        actual_dow = (dow - 1) if abs_hour < 0 else dow
        if abs_hour < 0:
            actual_hour = 24 + abs_hour
        else:
            actual_hour = abs_hour
        actual_dow = actual_dow % 7

        row = {
            'ap_code': ap_code,
            'hour_sin': np.sin(2 * np.pi * actual_hour / 24),
            'hour_cos': np.cos(2 * np.pi * actual_hour / 24),
            'day_sin': np.sin(2 * np.pi * actual_dow / 7),
            'day_cos': np.cos(2 * np.pi * actual_dow / 7),
        }

        # Fill numeric features from profiles
        ap_profile = ap_profiles.get(matched_key, {})
        dow_str = str(actual_dow)
        dow_data = ap_profile.get(dow_str, {})
        hour_str = str(actual_hour)
        hour_data = dow_data.get(hour_str, None)

        if hour_data:
            for feat in numeric_feats:
                row[feat] = float(hour_data.get(feat, 0.5))
        else:
            for feat in numeric_feats:
                row[feat] = 0.5

        feat_rows.append(row)

    # Build DataFrame and scale
    import pandas as pd
    input_df = pd.DataFrame(feat_rows)
    # Ensure column order matches scaler
    input_scaled = _predictor5_scaler.transform(input_df[all_feats])
    X_input = np.expand_dims(input_scaled, axis=0).astype(np.float32)

    # Predict
    device = next(_predictor5_model.parameters()).device
    with torch.no_grad():
        X_tensor = torch.tensor(X_input, dtype=torch.float32).to(device)
        pred_scaled = _predictor5_model(X_tensor).cpu().numpy()[0]

    # Inverse transform (only target column)
    dummy = np.zeros((len(pred_scaled), len(all_feats)))
    dummy[:, target_idx] = pred_scaled
    pred_scores = _predictor5_scaler.inverse_transform(dummy)[:, target_idx]
    pred_scores = np.clip(pred_scores, 0, 1)

    # Map predictions back to booking hours
    # pred_scores[0] = score at start_hour+0, pred_scores[1] = start_hour+1, etc.
    hourly_scores = {}
    labels_for_hours = []
    for i, h in enumerate(range(start_hour, end_hour)):
        if i < len(pred_scores):
            score = float(pred_scores[i])
            label = _signal_score_to_label(score)
            hourly_scores[h] = {'score': score, 'label': label}
            labels_for_hours.append(label)

    if not labels_for_hours:
        return None

    # Worst label = overall performance
    perf_rank_map = PERF_RANK
    worst_label = min(labels_for_hours, key=lambda lbl: perf_rank_map.get(lbl, 0))

    return {
        'label': worst_label,
        'hourly_scores': hourly_scores,
    }


def _load_signal_strength_model():
    import joblib
    global _signal_strength_model
    if _signal_strength_model is None:
        path = MODELS_DIR / "signal_strength_model.joblib"
        if not path.exists():
            raise FileNotFoundError(f"Signal strength model not found: {path}")
        _signal_strength_model = joblib.load(path)
    return _signal_strength_model


def _load_signal_strength_meta():
    from joblib import load as _jl_load
    global _signal_strength_meta
    if _signal_strength_meta is None:
        path = MODELS_DIR / "signal_strength_meta.joblib"
        if path.exists():
            _signal_strength_meta = _jl_load(path)
    return _signal_strength_meta or {}


def _load_geojson() -> dict:
    global _geojson_data
    if _geojson_data is None:
        if not GEOJSON_PATH.exists():
            raise FileNotFoundError(f"GeoJSON file not found: {GEOJSON_PATH}")
        with open(GEOJSON_PATH) as f:
            _geojson_data = json.load(f)
    return _geojson_data


def _build_ap_index() -> list[dict]:
    global _ap_index, _ap_index_by_name
    if _ap_index is not None:
        return _ap_index
    geojson = _load_geojson()
    _ap_index = []
    _ap_index_by_name = {}
    seen_ids = {}
    for feature in geojson["features"]:
        props = feature["properties"]
        coords = feature["geometry"]["coordinates"]
        ap_name = props.get("USER_NOM_A", "Unknown")
        espacio = props.get("USER_Espai", "")
        # Build a unique ID from AP name + espacio (room code)
        unique_id = f"{ap_name}_{espacio}" if espacio else ap_name
        # Handle duplicate AP names by appending a counter
        if unique_id in seen_ids:
            seen_ids[unique_id] += 1
            unique_id = f"{unique_id}_{seen_ids[unique_id]}"
        else:
            seen_ids[unique_id] = 0
        _ap_index.append({
            "id": unique_id,
            "name": ap_name,
            "lat": float(coords[1]),
            "lng": float(coords[0]),
            "building": props.get("USER_EDIFI", props.get("Nom_Edific", "Unknown")),
            "floor": float(props.get("Num_Planta", 0) or 0),
            "espacio": espacio,
        })
        # Build O(1) lookup
        ap_key = ap_name.strip().lower()
        if ap_key not in _ap_index_by_name:
            _ap_index_by_name[ap_key] = _ap_index[-1]
    return _ap_index


def _get_buildings_list() -> list[str]:
    global _buildings_list
    if _buildings_list is not None:
        return _buildings_list
    index = _build_ap_index()
    buildings = sorted({ap["building"] for ap in index if ap["building"] != "Unknown"})
    _buildings_list = buildings
    return _buildings_list


def _validate_day(day: str) -> str:
    day_lower = day.strip().lower()
    if day_lower in DAY_NAMES:
        return day_lower
    if day_lower in DAY_FULL_NAMES:
        return DAY_FULL_NAMES[day_lower]
    raise HTTPException(status_code=400, detail=f"Invalid day: '{day}'. Must be one of {DAY_NAMES}")


def _validate_hour(hour: int) -> int:
    if not isinstance(hour, int) or hour < 0 or hour > 23:
        raise HTTPException(status_code=400, detail=f"Invalid hour: {hour}. Must be an integer between 0 and 23.")
    return hour


def _get_heatmap_filepath(day: str, hour: int) -> Path:
    effective_hour = NIGHT_REPRESENTATIVE_HOUR if hour < 7 else hour
    return PRECOMPUTED_DIR / day / f"heatmap_h{effective_hour}.json"


def _load_heatmap_file(day: str, hour: int) -> dict:
    """Load heatmap from disk (no in-memory cache)."""
    filepath = _get_heatmap_filepath(day, hour)
    if not filepath.exists():
        raise HTTPException(status_code=404, detail=f"Heatmap not found for {day} hour {hour}")
    with open(filepath) as f:
        data = json.load(f)
    data["hour"] = hour
    return data


def _normalize_text(text: str) -> str:
    """Normalize text by removing diacritics (accents) and converting to lowercase."""
    import unicodedata
    # Normalize to NFKD form which separates base characters from diacritics
    nfkd = unicodedata.normalize('NFKD', text)
    # Remove combining diacritical marks (accents, cedillas, etc.)
    return ''.join(c for c in nfkd if not unicodedata.combining(c)).lower()


def _encode_building(building_name: str) -> int:
    encoder = _load_building_encoder()
    meta = _load_signal_strength_meta()
    buildings_list = meta.get("buildings", [])
    if encoder is not None and building_name in encoder.classes_:
        return int(encoder.transform([building_name])[0])
    # Try exact match with encoder classes (case-insensitive)
    if encoder is not None:
        for cls in encoder.classes_:
            if building_name.lower() == cls.lower():
                return int(encoder.transform([cls])[0])
    # Try fuzzy match with buildings_list
    norm_building = _normalize_text(building_name)
    for i, b in enumerate(buildings_list):
        norm_b = _normalize_text(b)
        if norm_building in norm_b or norm_b in norm_building:
            return i
    # Try fuzzy match with encoder classes
    if encoder is not None:
        for i, cls in enumerate(encoder.classes_):
            norm_cls = _normalize_text(cls)
            if norm_building in norm_cls or norm_cls in norm_building:
                return i
    return 0


def _dbm_to_quality(dbm: float) -> dict:
    if dbm >= -50:
        return {"quality": "Excellent", "bars": 5}
    elif dbm >= -60:
        return {"quality": "Good", "bars": 4}
    elif dbm >= -70:
        return {"quality": "Fair", "bars": 3}
    elif dbm >= -80:
        return {"quality": "Weak", "bars": 2}
    else:
        return {"quality": "Very Poor", "bars": 1}


def _dbm_to_status(dbm: float) -> str:
    """Convert signal dBm to predicted Up/Down status.
    Signal >= -75 dBm → likely Up (usable connection)
    Signal < -75 dBm → likely Down (too weak for reliable use)
    """
    return "Up" if dbm >= -75 else "Down"


def _dbm_to_status_confidence(dbm: float) -> float:
    """Confidence of the status prediction based on how far from threshold."""
    # -75 dBm threshold, confidence scales with distance from threshold
    diff = dbm - (-75)
    # Clamp confidence between 0.5 and 0.99
    confidence = min(0.99, max(0.5, 0.5 + abs(diff) / 50))
    return round(confidence, 3)


def _smooth_series(values: list, window: int = 3) -> list:
    n = len(values)
    if n < 3 or window < 3:
        return list(values)
    if window == 3:
        weights = [0.25, 0.5, 0.25]
    elif window == 5:
        weights = [0.1, 0.2, 0.4, 0.2, 0.1]
    else:
        half = window // 2
        weights = []
        for i in range(window):
            w = 1.0 - abs(i - half) / (half + 1)
            weights.append(w)
        total = sum(weights)
        weights = [w / total for w in weights]
    half = len(weights) // 2
    smoothed = []
    for i in range(n):
        total_w = 0.0
        total_v = 0.0
        for j, w in enumerate(weights):
            idx = i + j - half
            if 0 <= idx < n:
                total_w += w
                total_v += w * values[idx]
        smoothed.append(total_v / total_w if total_w > 0 else values[i])
    return smoothed


def _smooth_actual_hourly(hourly_dict: dict, min_samples: int = 20) -> dict:
    if not hourly_dict:
        return hourly_dict
    raw_values = []
    sample_counts = []
    for h in range(24):
        if h in hourly_dict:
            raw_values.append(hourly_dict[h]["actual_mean"])
            sample_counts.append(hourly_dict[h]["samples"])
        else:
            raw_values.append(None)
            sample_counts.append(0)
    filled = list(raw_values)
    known_indices = [i for i, v in enumerate(filled) if v is not None]
    if len(known_indices) >= 2:
        for h in range(24):
            if filled[h] is None:
                before = [i for i in known_indices if i < h]
                after = [i for i in known_indices if i > h]
                if before and after:
                    hb, ha = before[-1], after[0]
                    ratio = (h - hb) / (ha - hb)
                    filled[h] = filled[hb] + (filled[ha] - filled[hb]) * ratio
                elif before:
                    filled[h] = filled[before[-1]]
                elif after:
                    filled[h] = filled[after[0]]
    elif len(known_indices) == 1:
        v = filled[known_indices[0]]
        filled = [v] * 24
    smoothed_filled = list(filled)
    for h in range(24):
        if hourly_dict.get(h, {}).get("samples", 0) < min_samples and sample_counts[h] > 0:
            neighbor_weight = min(0.8, 1.0 - sample_counts[h] / min_samples)
            neighbor_sum = 0
            neighbor_count = 0
            for dh in [-2, -1, 1, 2]:
                nh = h + dh
                if 0 <= nh < 24 and filled[nh] is not None:
                    neighbor_sum += filled[nh]
                    neighbor_count += 1
            if neighbor_count > 0:
                neighbor_avg = neighbor_sum / neighbor_count
                smoothed_filled[h] = filled[h] * (1 - neighbor_weight) + neighbor_avg * neighbor_weight
    smoothed_values = _smooth_series(smoothed_filled, window=3)
    smoothed_values = _smooth_series(smoothed_values, window=3)
    result = {}
    for h in range(24):
        result[h] = {
            "actual_mean": round(smoothed_values[h], 1),
            "samples": sample_counts[h],
            "interpolated": raw_values[h] is None,
            "smoothed": sample_counts[h] < min_samples,
        }
    return result


def _haversine_distance(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    R = 6371000
    dlat = math.radians(lat2 - lat1)
    dlng = math.radians(lng2 - lng1)
    a = (math.sin(dlat / 2) ** 2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlng / 2) ** 2)
    c = 2 * math.asin(math.sqrt(a))
    return R * c


def _approximate_distance(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    lat_diff = (lat2 - lat1) * 111_320
    lng_diff = (lng2 - lng1) * 111_320 * abs(math.cos(math.radians((lat1 + lat2) / 2)))
    return math.sqrt(lat_diff ** 2 + lng_diff ** 2)


def _build_signal_features(building_code: int, floor: float, hour: float, day_of_week: float, is_weekend: float, day_of_month: float, month: float, ap_name_code: int = 0) -> dict:
    return {"building_code": building_code, "floor": floor, "hour": hour, "band": 5.0, "day_of_week": day_of_week, "is_weekend": is_weekend, "day_of_month": day_of_month, "month": month, "ap_name_code": ap_name_code}


def _build_v3_decision_features(hour: float, day_of_week: float, is_weekend: float, day_of_month: float, month: float, building_code: int, floor: float, lat: float, lng: float, predicted_signal_db: float) -> list[list[float]]:
    return [[hour, day_of_week, is_weekend, month, day_of_month, building_code, floor, lat, lng, predicted_signal_db]]


def _find_ap_in_index(ap_name: str) -> Optional[dict]:
    _build_ap_index()
    cache_key = ap_name.strip().lower()
    return _ap_index_by_name.get(cache_key)


def _predict_signal_for_ap(ap_entry: dict, hour: float, day_of_week: float, is_weekend: float, day_of_month: float, month: float) -> float:
    import pandas as pd
    model = _load_signal_strength_model()
    building_code = _encode_building(ap_entry["building"])
    ap_name_code = _encode_ap_name(ap_entry["name"])
    features = _build_signal_features(building_code=building_code, floor=ap_entry["floor"], hour=hour, day_of_week=day_of_week, is_weekend=is_weekend, day_of_month=day_of_month, month=month, ap_name_code=ap_name_code)
    df = pd.DataFrame([features])
    return float(model.predict(df)[0])


# --- Booking helper functions ---

def _build_room_lookup():
    """Build a lookup dict mapping room codes to AP info from GeoJSON."""
    global _room_lookup
    if _room_lookup:
        return _room_lookup
    geojson = _load_geojson()
    for feature in geojson["features"]:
        props = feature["properties"]
        room_code = str(props.get("USER_Espai", "")).strip().upper()
        if room_code:
            _room_lookup[room_code] = {
                "ap_name": str(props.get("USER_NOM_A", "")).strip().upper(),
                "building": props.get("USER_EDIFI", ""),
                "floor": props.get("Num_Planta", 0),
            }
    return _room_lookup


def _get_ap_from_room(room_code: str) -> Optional[dict]:
    lookup = _build_room_lookup()
    return lookup.get(room_code.strip().upper())


def _check_booking_availability(bookings: list, room_code: str, date_str: str, start_hour: int, end_hour: int) -> tuple[bool, Optional[dict]]:
    room_code_upper = room_code.strip().upper()
    for book in bookings:
        if book["room_code"] != room_code_upper or book["date"] != date_str:
            continue
        if not (end_hour <= book["start_hour"] or start_hour >= book["end_hour"]):
            return False, book
    return True, None


def _apply_perf_penalty(label: str, steps: int) -> str:
    """Apply a performance penalty by stepping down the label by `steps` ranks."""
    rank_order = ['Very Poor', 'Weak', 'Poor', 'Fair', 'Good', 'Excellent', 'Excellent+', 'Excellent++']
    try:
        idx = rank_order.index(label)
    except ValueError:
        return label  # Unknown label, return as-is
    new_idx = max(0, idx - steps)
    return rank_order[new_idx]


def _predict_booking_performance(room_code: str, date_str: str, start_hour: int, end_hour: int, n_students: int) -> dict:
    """Predict performance for a booking slot using dual-model comparison.

    Strategy:
      1. Try Predictor5_0 LSTM (时序感知, 无时间限制, 269 APs).
      2. Fall back to signal_strength RandomForest (建筑级, 5h limit,
         所有 AP).
      3. If both available, predict signal_db via RF → convert to label,
         compare with LSTM label, pick more confident one.

    Returns dict with performance, model_source, predictions.
    """
    ap_info = _get_ap_from_room(room_code)
    if ap_info is None:
        return {"ap_name": "Unknown", "performance": None,
                "warning": "Room not found", "model_source": None}

    ap_name = ap_info["ap_name"]
    ap_entry = _find_ap_in_index(ap_name)

    # ── Check for past slot ──
    booking_dt = datetime.strptime(f"{date_str} {start_hour:02d}:00", "%Y-%m-%d %H:%M")
    hours_until = (booking_dt - datetime.now()).total_seconds() / 3600
    if hours_until < 0:
        return {"ap_name": ap_name, "performance": None,
                "warning": "Cannot predict for a past time slot",
                "model_source": None}

    # ── Strategy 1: Try LSTM first (no time limit!) ──
    lstm_result = _predict_lstm_for_booking(ap_name, date_str, start_hour, end_hour)
    lstm_available = lstm_result is not None

    # ── Strategy 2: RandomForest fallback ──
    rf_available = False
    rf_label = None
    rf_predictions = None

    if ap_entry is not None:
        try:
            signal_model = _load_signal_strength_model()
            rf_available = True
        except FileNotFoundError:
            rf_available = False

    if rf_available and ap_entry is not None:
        booking_date = datetime.strptime(date_str, "%Y-%m-%d")
        day_of_week = float(booking_date.weekday())
        is_weekend = 1.0 if day_of_week >= 5 else 0.0
        day_of_month = float(booking_date.day)
        month = float(booking_date.month)
        building_code = _encode_building(ap_entry["building"])
        ap_name_code = _encode_ap_name(ap_entry["name"])
        hours = list(range(start_hour, end_hour))

        import pandas as pd
        rf_preds = []
        for h in hours:
            features = _build_signal_features(
                building_code=building_code, floor=ap_entry["floor"],
                hour=float(h), day_of_week=day_of_week,
                is_weekend=is_weekend, day_of_month=day_of_month,
                month=month, ap_name_code=ap_name_code
            )
            df = pd.DataFrame([features])
            signal_db = float(signal_model.predict(df)[0])
            quality = _dbm_to_quality(signal_db)["quality"]
            rf_preds.append((h, quality))

        if rf_preds:
            rf_predictions = rf_preds
            rf_label = min(rf_preds, key=lambda x: PERF_RANK.get(x[1], 0))[1]

    # ── Choose best result ──
    if lstm_available and rf_available:
        # Dual-model: compare LSTM label vs RF label
        lstm_label = lstm_result['label']
        lstm_rank = PERF_RANK.get(lstm_label, 0)
        rf_rank_val = PERF_RANK.get(rf_label, 0)

        # If LSTM gives significantly different (more pessimistic) result,
        # or if LSTM is more optimistic, prefer LSTM (it's more precise:
        # test MAE=0.0125 on signal_score vs RF MAE~3-5 dBm on signal_db).
        # LSTM is trained on 269 APs, RF covers all APs.
        # If ranks differ by >= 2, LSTM is more confident → use it.
        # Otherwise: if LSTM rank >= RF rank, use LSTM (same or better).
        # If RF better and LSTM very different, could be LSTM not trained on this AP.
        if lstm_rank >= rf_rank_val or abs(lstm_rank - rf_rank_val) <= 1:
            chosen_label = lstm_label
            source = 'lstm'
            hourly_preds = [(h, lstm_result['hourly_scores'][h]['label'])
                            for h in range(start_hour, end_hour)
                            if h in lstm_result['hourly_scores']]
        else:
            chosen_label = rf_label
            source = 'rf'
            hourly_preds = rf_predictions

    elif lstm_available:
        chosen_label = lstm_result['label']
        source = 'lstm'
        hourly_preds = [(h, lstm_result['hourly_scores'][h]['label'])
                        for h in range(start_hour, end_hour)
                        if h in lstm_result['hourly_scores']]
    elif rf_available and rf_label is not None:
        chosen_label = rf_label
        source = 'rf'
        hourly_preds = rf_predictions
    else:
        return {"ap_name": ap_name, "performance": None,
                "warning": "No prediction model available",
                "model_source": None}

    # ── Apply n_students overload penalty ──
    # Many students connecting to the same AP can degrade performance.
    # LSTM was trained with client_count, but during inference we don't
    # have a clean way to inject it into the LSTM window. Instead we
    # apply an empirical penalty after prediction.
    if chosen_label is not None:
        penalty = 0
        if n_students > 100:
            penalty = 2
        elif n_students > 50:
            penalty = 1

        if penalty > 0:
            rank = PERF_RANK.get(chosen_label, 0)
            deg_label = _apply_perf_penalty(chosen_label, penalty)
            if deg_label != chosen_label:
                chosen_label = deg_label
                # Also degrade hourly predictions
                if hourly_preds:
                    hourly_preds = [
                        (h, _apply_perf_penalty(lbl, penalty))
                        for h, lbl in hourly_preds
                    ]

    return {
        "ap_name": ap_name,
        "performance": chosen_label,
        "predictions": hourly_preds,
        "warning": None,
        "model_source": source,
    }


def _suggest_best_slot(room_code: str, date_str: str, duration_hours: int, n_students: int) -> Optional[dict]:
    """Find the best available time slot for a given room and duration."""
    results = []
    for start in range(7, 23 - duration_hours):
        end = start + duration_hours
        available, _ = _check_booking_availability(_bookings, room_code, date_str, start, end)
        if not available:
            continue
        pred = _predict_booking_performance(room_code, date_str, start, end, n_students)
        if pred.get("warning"):
            continue
        results.append((start, end, pred["performance"]))

    if not results:
        return None
    best = max(results, key=lambda x: PERF_RANK.get(x[2], 0))
    return {"start_hour": best[0], "end_hour": best[1], "performance": best[2]}


def _suggest_alternative_rooms(room_code: str, date_str: str, start_hour: int, end_hour: int, n_students: int, min_perf: str) -> list[dict]:
    """Find alternative rooms on the same building/floor with better performance."""
    current = _get_ap_from_room(room_code)
    if current is None:
        return []

    lookup = _build_room_lookup()
    candidates = []
    visited_aps = set()

    for code, info in lookup.items():
        if (info["building"] == current["building"]
                and info["floor"] == current["floor"]
                and code != room_code.strip().upper()):
            ap_name = info["ap_name"]
            if ap_name in visited_aps:
                continue
            available, _ = _check_booking_availability(_bookings, code, date_str, start_hour, end_hour)
            if not available:
                continue
            pred = _predict_booking_performance(code, date_str, start_hour, end_hour, n_students)
            if pred is None or pred["warning"]:
                continue
            if pred["performance"] and PERF_RANK.get(pred["performance"], 0) >= PERF_RANK.get(min_perf, 0):
                candidates.append({"room_code": code, "performance": pred["performance"]})
                visited_aps.add(ap_name)

    return sorted(candidates, key=lambda x: PERF_RANK.get(x["performance"], 0), reverse=True)


class PredictRequestV3(BaseModel):

    model_config = {"extra": "ignore"}
    ap_name: str = Field(default="", description="AP name (e.g. AP-FTI02)")
    hour: float = Field(default=12, description="Hour of day (0-23)")
    day_of_week: float = Field(default=0, description="Day of week (0=Mon, 6=Sun)")
    is_weekend: float = Field(default=0, description="Is weekend (0 or 1)")
    month: float = Field(default=4, description="Month (1-12)")
    day_of_month: float = Field(default=15, description="Day of month")


class RecommendRequest(BaseModel):
    lat: float
    lng: float
    radius: int = Field(default=500, ge=50, le=2000)
    mode: str = Field(default="balanced", pattern="^(distance|signal|balanced)$")
    building: str = Field(default="")
    prefer_stable: bool = Field(default=True)

    @field_validator('lat')
    @classmethod
    def validate_lat(cls, v):
        if v < -90 or v > 90:
            raise ValueError('Latitude must be between -90 and 90')
        return v

    @field_validator('lng')
    @classmethod
    def validate_lng(cls, v):
        if v < -180 or v > 180:
            raise ValueError('Longitude must be between -180 and 180')
        return v

    @field_validator('building')
    @classmethod
    def validate_building(cls, v):
        if len(v) > 100:
            raise ValueError('Building name too long (max 100 characters)')
        return v


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request, exc):
    errors = []
    for error in exc.errors():
        errors.append({
            "field": " -> ".join(str(loc) for loc in error["loc"]),
            "message": error["msg"],
            "type": error["type"],
        })
    return JSONResponse(
        status_code=422,
        content={
            "detail": "Input validation failed",
            "errors": errors,
            "model_version": "v3"
        }
    )


@app.get("/health")
async def health():
    return {"status": "ok", "timestamp": time.time(), "precomputed_days": len(DAY_NAMES), "precomputed_hours": 24, "model_version": "v3"}


@app.get("/status")
async def server_status():
    models_loaded = {
        "decision_tree_v3": _decision_tree_v3 is not None,
        "building_encoder": _building_encoder is not None,
        "signal_strength_model": _signal_strength_model is not None,
        "geojson": _geojson_data is not None,
        "ap_index": _ap_index is not None,
    }
    return {"status": "ok", "timestamp": time.time(), "model_version": "v3", "models": models_loaded, "cache": {"strategy": "no_in_memory_cache"}, "precomputed": {"days": DAY_NAMES, "hours": list(range(24)), "night_representative_hour": NIGHT_REPRESENTATIVE_HOUR}}


@app.post("/predict")
async def predict_ap_status(request: PredictRequestV3):
    """
    v3 model - uses only features available at inference time
    Request only needs ap_name + time features; rest is auto-filled from GeoJSON and signal model
    """
    try:
        model = _load_decision_tree_v3()
    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))

    ap_entry = _find_ap_in_index(request.ap_name)
    if ap_entry is None:
        raise HTTPException(status_code=404, detail=f"AP '{request.ap_name}' not found in GeoJSON database.")

    building_code = _encode_building(ap_entry["building"])
    floor = ap_entry["floor"]
    lat = ap_entry["lat"]
    lng = ap_entry["lng"]

    try:
        predicted_signal_db = _predict_signal_for_ap(ap_entry=ap_entry, hour=request.hour, day_of_week=request.day_of_week, is_weekend=request.is_weekend, day_of_month=request.day_of_month, month=request.month)
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Signal prediction failed: {str(e)}")

    features = _build_v3_decision_features(hour=request.hour, day_of_week=request.day_of_week, is_weekend=request.is_weekend, day_of_month=request.day_of_month, month=request.month, building_code=building_code, floor=floor, lat=lat, lng=lng, predicted_signal_db=predicted_signal_db)

    import pandas as pd
    # Use DataFrame with proper column names to avoid sklearn feature name warnings
    v3_feature_names = ['hour', 'day_of_week', 'is_weekend', 'month', 'day_of_month',
                        'building_code', 'floor', 'lat', 'lng', 'predicted_signal_db']
    features_df = pd.DataFrame(features, columns=v3_feature_names)

    prediction = model.predict(features_df)[0]
    probability = model.predict_proba(features_df)[0].tolist()
    confidence = max(probability)

    return {
        "prediction": "Up" if prediction == 1 else "Down",
        "confidence": round(confidence, 3),
        "probability": probability,
        "model_version": "v3",
        "ap_info": {"name": request.ap_name, "building": ap_entry["building"], "floor": int(floor), "lat": lat, "lng": lng},
        "features_used": {
            "time": {"hour": request.hour, "day_of_week": request.day_of_week, "is_weekend": request.is_weekend, "month": request.month, "day_of_month": request.day_of_month},
            "ap_static": {"building_code": building_code, "floor": floor, "lat": lat, "lng": lng},
            "cascade": {"predicted_signal_db": round(predicted_signal_db, 1)},
        },
    }


@app.get("/predict/signal_strength/heatmap")
async def get_signal_heatmap(hour: int = Query(default=12, description="Hour of day (0-23)"), day: str = Query(default="mon", description="Day of week (mon/tue/wed/thu/fri/sat/sun)")):
    day_key = _validate_day(day)
    validated_hour = _validate_hour(hour)
    try:
        data = _load_heatmap_file(day_key, validated_hour)
        return JSONResponse(content=data)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load heatmap: {str(e)}")


@app.get("/predict/signal_strength/buildings")
async def get_buildings():
    try:
        buildings = _get_buildings_list()
        return {"buildings": buildings, "total": len(buildings)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load buildings: {str(e)}")


@app.get("/predict/signal_strength/ap_trend/{ap_name:path}")
async def get_ap_daily_trend(ap_name: str):
    cache_key = ap_name.strip().lower()
    
    # Try file cache first
    trend_file = TRENDS_DIR / f"{cache_key}.json"
    if trend_file.exists():
        try:
            with open(trend_file) as f:
                cached = json.load(f)
            if time.time() - cached.get("_cached_at", 0) < TREND_FILE_TTL:
                # Strip internal metadata and return
                return {k: v for k, v in cached.items() if not k.startswith("_")}
        except Exception:
            pass  # Treat corrupt file as cache miss
    
    try:
        model = _load_signal_strength_model()
    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))
    ap_entry = _find_ap_in_index(ap_name)
    if ap_entry is None:
        raise HTTPException(status_code=404, detail=f"AP '{ap_name}' not found")
    building = ap_entry["building"]
    floor = ap_entry["floor"]
    building_code = _encode_building(building)
    
    # Use current date for trend prediction
    today = datetime.now()
    day_of_week = float(today.weekday())  # 0=Mon, 6=Sun
    is_weekend = 1.0 if day_of_week >= 5 else 0.0
    day_of_month = float(today.day)
    month = float(today.month)
    day_name = DAY_NAMES[int(day_of_week)]  # e.g. 'mon', 'tue', ..., 'sun'
    day_type = "weekend" if is_weekend else "weekday"
    
    # On-demand inference (no in-memory cache, just compute)
    import pandas as pd
    ap_name_code = _encode_ap_name(ap_entry["name"])
    rows = []
    for hour in range(24):
        rows.append(_build_signal_features(building_code=building_code, floor=floor, hour=float(hour), day_of_week=day_of_week, is_weekend=is_weekend, day_of_month=day_of_month, month=month, ap_name_code=ap_name_code))
    df = pd.DataFrame(rows)
    predictions = model.predict(df)
    # Smooth raw predictions to reduce spikiness
    smoothed = _smooth_series([float(p) for p in predictions], window=5)
    hourly_data = []
    signal_values = []
    for hour, signal_db in enumerate(smoothed):
        quality_info = _dbm_to_quality(float(signal_db))
        status = _dbm_to_status(float(signal_db))
        status_conf = _dbm_to_status_confidence(float(signal_db))
        hourly_data.append({
            "hour": hour,
            "signal_db": round(float(signal_db), 1),
            "signal_quality": quality_info["quality"],
            "bars": quality_info["bars"],
            "predicted_status": status,
            "status_confidence": status_conf,
        })
        signal_values.append(round(float(signal_db), 1))
    avg_db = sum(signal_values) / len(signal_values) if signal_values else 0
    max_db = max(signal_values) if signal_values else 0
    min_db = min(signal_values) if signal_values else 0
    best_hour = signal_values.index(max_db) if signal_values else 0
    worst_hour = signal_values.index(min_db) if signal_values else 0

    # Calculate accuracy from feedback data if available
    ap_feedback = [f for f in _prediction_feedback if f["ap_name"].strip().lower() == cache_key]
    accuracy_stats = {}
    if ap_feedback:
        correct = sum(1 for f in ap_feedback if f["predicted"] == f["actual"])
        total = len(ap_feedback)
        accuracy_stats = {
            "total_feedback": total,
            "correct": correct,
            "accuracy": round(correct / total, 3) if total > 0 else 0,
            "up_accuracy": 0,
            "down_accuracy": 0,
        }
        up_feedback = [f for f in ap_feedback if f["actual"] == "Up"]
        down_feedback = [f for f in ap_feedback if f["actual"] == "Down"]
        if up_feedback:
            accuracy_stats["up_accuracy"] = round(
                sum(1 for f in up_feedback if f["predicted"] == "Up") / len(up_feedback), 3
            )
        if down_feedback:
            accuracy_stats["down_accuracy"] = round(
                sum(1 for f in down_feedback if f["predicted"] == "Down") / len(down_feedback), 3
            )

    # Calculate accuracy vs actual measurements from clientes_processed.csv
    actual_data = _load_actual_signal_data().get(cache_key, {})
    accuracy_vs_actual = None
    if actual_data and actual_data.get("hourly"):
        # Apply smoothing to actual measurements for a more stable comparison
        hourly_actual = _smooth_actual_hourly(actual_data["hourly"], min_samples=20)
        
        # --- Interpolate missing hours to get a full 24-hour curve ---
        # Build a complete 0..23 array, filling gaps with linear interpolation
        full_actual = {}
        # hourly_actual keys are already int (converted in _load_actual_signal_data)
        actual_hours = sorted(hourly_actual.keys())
        
        if len(actual_hours) >= 2:
            # Interpolate between known points
            for h in range(24):
                try:
                    if h in hourly_actual:
                        full_actual[h] = {
                            "actual_mean": hourly_actual[h]["actual_mean"],
                            "samples": hourly_actual[h]["samples"],
                            "interpolated": False,
                        }
                    else:
                        # Find nearest known hours before and after
                        before = [ah for ah in actual_hours if ah < h]
                        after = [ah for ah in actual_hours if ah > h]
                        
                        if before and after:
                            h_before = before[-1]
                            h_after = after[0]
                            v_before = hourly_actual[h_before]["actual_mean"]
                            v_after = hourly_actual[h_after]["actual_mean"]
                            # Linear interpolation
                            ratio = (h - h_before) / (h_after - h_before)
                            interpolated = v_before + (v_after - v_before) * ratio
                            full_actual[h] = {
                                "actual_mean": round(interpolated, 1),
                                "samples": 0,
                                "interpolated": True,
                            }
                        elif before and not after:
                            # Extrapolate from last known value (flat)
                            full_actual[h] = {
                                "actual_mean": hourly_actual[before[-1]]["actual_mean"],
                                "samples": 0,
                                "interpolated": True,
                            }
                        elif after and not before:
                            # Extrapolate from first known value (flat)
                            full_actual[h] = {
                                "actual_mean": hourly_actual[after[0]]["actual_mean"],
                                "samples": 0,
                                "interpolated": True,
                            }
                except Exception:
                    full_actual[h] = {"actual_mean": 0, "samples": 0, "interpolated": True}
        elif len(actual_hours) == 1:
            # Only one hour known — use it for all hours
            single_h = actual_hours[0]
            single_v = hourly_actual[single_h]["actual_mean"]
            for h in range(24):
                full_actual[h] = {
                    "actual_mean": single_v,
                    "samples": hourly_actual[single_h]["samples"] if h == single_h else 0,
                    "interpolated": h != single_h,
                }
        else:
            full_actual = {k: v for k, v in hourly_actual.items()}
        
        # Now build comparison using the full 24-hour actual data
        diffs = []
        actual_hourly_list = []
        for h_data in hourly_data:
            h = h_data["hour"]
            if h in full_actual:
                pred_db = h_data["signal_db"]
                actual_db = full_actual[h]["actual_mean"]
                diff = abs(pred_db - actual_db)
                diffs.append(diff)
                actual_hourly_list.append({
                    "hour": h,
                    "actual_mean": actual_db,
                    "samples": full_actual[h].get("samples", 0),
                    "predicted_db": pred_db,
                    "diff": round(diff, 1),
                    "interpolated": full_actual[h].get("interpolated", False),
                })
        
        if diffs:
            mae = sum(diffs) / len(diffs)
            within_5db = sum(1 for d in diffs if d <= 5)
            within_10db = sum(1 for d in diffs if d <= 10)
            signal_accuracy = within_5db / len(diffs)
            
            # Also compute status accuracy (Up/Down based on -75 threshold)
            status_correct = 0
            status_total = 0
            for h_data in hourly_data:
                h = h_data["hour"]
                if h in full_actual:
                    pred_status = _dbm_to_status(h_data["signal_db"])
                    actual_status = _dbm_to_status(full_actual[h]["actual_mean"])
                    if pred_status == actual_status:
                        status_correct += 1
                    status_total += 1
            
            accuracy_vs_actual = {
                "mae": round(mae, 1),
                "signal_accuracy": round(signal_accuracy, 3),
                "within_5db": within_5db,
                "within_10db": within_10db,
                "compared_hours": len(diffs),
                "total_measurements": actual_data["total_measurements"],
                "status_accuracy": round(status_correct / status_total, 3) if status_total > 0 else None,
                "hourly": actual_hourly_list,
            }

    result = {
        "ap_name": ap_name,
        "building": building,
        "floor": int(floor),
        "lat": ap_entry["lat"],
        "lng": ap_entry["lng"],
        "trend": hourly_data,
        "day_type": day_type,
        "day_name": day_name,
        "stats": {
            "avg_db": round(avg_db, 1),
            "max_db": round(max_db, 1),
            "min_db": round(min_db, 1),
            "best_hour": best_hour,
            "worst_hour": worst_hour,
        },
        "accuracy": accuracy_stats,
        "accuracy_vs_actual": accuracy_vs_actual,
    }
    # Cache result to disk for future requests
    try:
        TRENDS_DIR.mkdir(parents=True, exist_ok=True)
        cached_for_file = dict(result)
        cached_for_file["_cached_at"] = time.time()
        with open(trend_file, "w") as f:
            json.dump(cached_for_file, f)
    except Exception:
        pass  # Non-critical write
    return result



class PredictFeedbackRequest(BaseModel):
    ap_name: str = Field(..., description="AP name")
    hour: int = Field(..., ge=0, le=23, description="Hour of prediction")
    predicted: str = Field(..., pattern="^(Up|Down)$", description="What the model predicted")
    actual: str = Field(..., pattern="^(Up|Down)$", description="What actually happened")


@app.post("/predict/feedback")
async def submit_prediction_feedback(request: PredictFeedbackRequest):
    """Submit user feedback on prediction accuracy."""
    feedback = {
        "ap_name": request.ap_name.strip(),
        "hour": request.hour,
        "predicted": request.predicted,
        "actual": request.actual,
        "timestamp": time.time(),
    }
    _prediction_feedback.append(feedback)
    # Keep only last 1000 entries per AP to manage memory
    ap_key = request.ap_name.strip().lower()
    ap_entries = [f for f in _prediction_feedback if f["ap_name"].strip().lower() == ap_key]
    if len(ap_entries) > 1000:
        excess = len(ap_entries) - 1000
        _prediction_feedback[:] = [
            f for f in _prediction_feedback
            if f["ap_name"].strip().lower() != ap_key or f not in ap_entries[:excess]
        ]
    return {
        "success": True,
        "feedback": feedback,
    }


@app.get("/predict/stats/{ap_name:path}")
async def get_prediction_stats(ap_name: str):
    """Get prediction accuracy statistics for a specific AP."""
    cache_key = ap_name.strip().lower()
    ap_feedback = [f for f in _prediction_feedback if f["ap_name"].strip().lower() == cache_key]
    if not ap_feedback:
        return {
            "ap_name": ap_name,
            "total_feedback": 0,
            "accuracy": None,
            "message": "No feedback data available for this AP yet."
        }
    correct = sum(1 for f in ap_feedback if f["predicted"] == f["actual"])
    total = len(ap_feedback)
    up_feedback = [f for f in ap_feedback if f["actual"] == "Up"]
    down_feedback = [f for f in ap_feedback if f["actual"] == "Down"]
    up_correct = sum(1 for f in up_feedback if f["predicted"] == "Up")
    down_correct = sum(1 for f in down_feedback if f["predicted"] == "Down")
    return {
        "ap_name": ap_name,
        "total_feedback": total,
        "correct": correct,
        "accuracy": round(correct / total, 3),
        "up_accuracy": round(up_correct / len(up_feedback), 3) if up_feedback else None,
        "down_accuracy": round(down_correct / len(down_feedback), 3) if down_feedback else None,
        "up_samples": len(up_feedback),
        "down_samples": len(down_feedback),
        "recent_feedback": sorted(ap_feedback, key=lambda x: x["timestamp"], reverse=True)[:10],
    }


@app.get("/predict/signal_strength/accuracy/{ap_name:path}")
async def get_ap_signal_accuracy(ap_name: str):
    """Get detailed prediction vs actual signal accuracy for a specific AP."""
    cache_key = ap_name.strip().lower()
    
    # Load actual data
    actual_data = _load_actual_signal_data().get(cache_key, {})
    if not actual_data or not actual_data.get("hourly"):
        return {
            "ap_name": ap_name,
            "has_data": False,
            "message": "No actual measurement data available for this AP.",
        }
    
    # Get predicted trend
    try:
        model = _load_signal_strength_model()
    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))
    
    ap_entry = _find_ap_in_index(ap_name)
    if ap_entry is None:
        return {
            "ap_name": ap_name,
            "has_data": False,
            "message": "AP not found in GeoJSON database.",
        }
    
    import pandas as pd
    building_code = _encode_building(ap_entry["building"])
    ap_name_code = _encode_ap_name(ap_entry["name"])
    rows = []
    for hour in range(24):
        rows.append(_build_signal_features(
            building_code=building_code, floor=ap_entry["floor"],
            hour=float(hour), day_of_week=0.0, is_weekend=0.0,
            day_of_month=15.0, month=4.0, ap_name_code=ap_name_code
        ))
    df = pd.DataFrame(rows)
    predictions = model.predict(df)
    
    hourly_actual = actual_data["hourly"]
    comparison = []
    diffs = []
    status_correct = 0
    status_total = 0
    
    for hour in range(24):
        pred_db = round(float(predictions[hour]), 1)
        pred_status = _dbm_to_status(pred_db)
        pred_quality = _dbm_to_quality(pred_db)["quality"]
        
        entry = {
            "hour": hour,
            "predicted_db": pred_db,
            "predicted_status": pred_status,
            "predicted_quality": pred_quality,
        }
        
        if hour in hourly_actual:
            actual_db = hourly_actual[hour]["actual_mean"]
            actual_status = _dbm_to_status(actual_db)
            actual_quality = _dbm_to_quality(actual_db)["quality"]
            diff = abs(pred_db - actual_db)
            diffs.append(diff)
            
            if pred_status == actual_status:
                status_correct += 1
            status_total += 1
            
            entry["actual_db"] = actual_db
            entry["actual_status"] = actual_status
            entry["actual_quality"] = actual_quality
            entry["actual_samples"] = hourly_actual[hour]["samples"]
            entry["diff"] = round(diff, 1)
        else:
            entry["actual_db"] = None
            entry["diff"] = None
        
        comparison.append(entry)
    
    # Calculate metrics
    mae = sum(diffs) / len(diffs) if diffs else None
    within_5db = sum(1 for d in diffs if d <= 5) if diffs else 0
    within_10db = sum(1 for d in diffs if d <= 10) if diffs else 0
    signal_accuracy = within_5db / len(diffs) if diffs else None
    status_accuracy = status_correct / status_total if status_total > 0 else None
    
    return {
        "ap_name": ap_name,
        "building": ap_entry["building"],
        "floor": int(ap_entry["floor"]),
        "has_data": True,
        "total_measurements": actual_data["total_measurements"],
        "compared_hours": len(diffs),
        "metrics": {
            "mae": round(mae, 1) if mae else None,
            "signal_accuracy": round(signal_accuracy, 3) if signal_accuracy else None,
            "within_5db": within_5db,
            "within_10db": within_10db,
            "status_accuracy": round(status_accuracy, 3) if status_accuracy else None,
        },
        "hourly_comparison": comparison,
    }


@app.get("/predict/signal_strength/ap_trend/{ap_name:path}/compare")
async def get_ap_trend_compare(ap_name: str):
    try:
        model = _load_signal_strength_model()
    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))
    ap_entry = _find_ap_in_index(ap_name)
    if ap_entry is None:
        raise HTTPException(status_code=404, detail=f"AP '{ap_name}' not found")
    building = ap_entry["building"]
    floor = ap_entry["floor"]
    building_code = _encode_building(building)
    ap_name_code = _encode_ap_name(ap_entry["name"])

    def _predict_for_day(day_of_week: float, is_weekend: float) -> list:
        import pandas as pd
        rows = []
        for hour in range(24):
            rows.append(_build_signal_features(building_code=building_code, floor=floor, hour=float(hour), day_of_week=day_of_week, is_weekend=is_weekend, day_of_month=15.0, month=4.0, ap_name_code=ap_name_code))
        df = pd.DataFrame(rows)
        predictions = model.predict(df)
        # Smooth predictions
        smoothed = _smooth_series([float(p) for p in predictions], window=5)
        result = []
        for hour, signal_db in enumerate(smoothed):
            quality_info = _dbm_to_quality(float(signal_db))
            result.append({"hour": hour, "signal_db": round(float(signal_db), 1), "signal_quality": quality_info["quality"], "bars": quality_info["bars"]})
        return result

    weekday_trend = _predict_for_day(0.0, 0.0)
    weekend_trend = _predict_for_day(5.0, 1.0)
    return {"ap_name": ap_name, "building": building, "weekday": {"label": "Weekday (Mon)", "trend": weekday_trend}, "weekend": {"label": "Weekend (Sat)", "trend": weekend_trend}}


@app.post("/recommend")
async def recommend_aps(request: RecommendRequest):
    try:
        signal_model = _load_signal_strength_model()
        decision_model = _load_decision_tree_v3()
    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))
    current_time = time.localtime()
    current_hour = float(current_time.tm_hour)
    current_day = float(current_time.tm_wday)
    current_day_of_month = float(current_time.tm_mday)
    current_month = float(current_time.tm_mon)
    is_weekend = 1.0 if current_time.tm_wday >= 5 else 0.0
    ap_index = _build_ap_index()
    nearby_aps = []
    for ap in ap_index:
        distance = _approximate_distance(request.lat, request.lng, ap["lat"], ap["lng"])
        if distance > request.radius:
            continue
        if request.building and request.building.lower() not in ap["building"].lower():
            continue
        ap["distance"] = round(distance, 1)
        nearby_aps.append(ap)
    if not nearby_aps:
        return {"recommendations": [], "message": "No APs found in the specified area"}
    import pandas as pd
    signal_rows = []
    for ap in nearby_aps:
        building_code = _encode_building(ap["building"])
        ap_name_code = _encode_ap_name(ap["name"])
        signal_rows.append(_build_signal_features(building_code=building_code, floor=ap["floor"], hour=current_hour, day_of_week=current_day, is_weekend=is_weekend, day_of_month=current_day_of_month, month=current_month, ap_name_code=ap_name_code))
    signal_df = pd.DataFrame(signal_rows)
    signal_predictions = signal_model.predict(signal_df)
    decision_rows = []
    for i, ap in enumerate(nearby_aps):
        building_code = _encode_building(ap["building"])
        decision_rows.append(_build_v3_decision_features(hour=current_hour, day_of_week=current_day, is_weekend=is_weekend, day_of_month=current_day_of_month, month=current_month, building_code=building_code, floor=ap["floor"], lat=ap["lat"], lng=ap["lng"], predicted_signal_db=float(signal_predictions[i]))[0])
    # Use DataFrame with proper column names to avoid sklearn feature name warnings
    v3_feature_names = ['hour', 'day_of_week', 'is_weekend', 'month', 'day_of_month',
                        'building_code', 'floor', 'lat', 'lng', 'predicted_signal_db']
    decision_df = pd.DataFrame(decision_rows, columns=v3_feature_names)
    status_predictions = decision_model.predict(decision_df)
    status_probabilities = decision_model.predict_proba(decision_df)
    results = []
    for i, ap in enumerate(nearby_aps):
        signal_db = float(signal_predictions[i])
        quality_info = _dbm_to_quality(signal_db)
        status_pred = int(status_predictions[i])
        status_prob = status_probabilities[i].tolist()
        signal_score = max(0, (signal_db + 100) / 50)
        distance_score = max(0, 1 - ap["distance"] / request.radius)
        if request.mode == "distance":
            score = distance_score * 0.8 + signal_score * 0.2
        elif request.mode == "signal":
            score = signal_score * 0.8 + distance_score * 0.2
        else:
            score = signal_score * 0.5 + distance_score * 0.5
        results.append({"id": ap["id"], "name": ap["name"], "lat": ap["lat"], "lng": ap["lng"], "building": ap["building"], "floor": int(ap["floor"]), "distance": ap["distance"], "signal_db": round(signal_db, 1), "signal_quality": quality_info["quality"], "bars": quality_info["bars"], "prediction": "Up" if status_pred == 1 else "Down", "confidence": round(max(status_prob), 3), "up_probability": round(status_prob[1] if len(status_prob) > 1 else status_prob[0], 3), "score": round(score, 3)})
    results.sort(key=lambda x: x["score"], reverse=True)
    return {"recommendations": results[:20], "total_found": len(results), "mode": request.mode, "radius": request.radius, "model_version": "v3"}


@app.get("/route/{lat}/{lng}/{dest_lat}/{dest_lng}")
async def get_route(lat: float, lng: float, dest_lat: float, dest_lng: float, acceptable_range: int = Query(default=500, ge=100, le=5000, alias="acceptable_range")):
    try:
        result = _find_route_path(lat, lng, dest_lat, dest_lng, acceptable_range)
        return result
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Route computation failed: {str(e)}")


@app.get("/route/advanced/{lat}/{lng}/{dest_lat}/{dest_lng}")
async def get_advanced_route(lat: float, lng: float, dest_lat: float, dest_lng: float, acceptable_range: int = Query(default=500, ge=100, le=5000, alias="acceptable_range")):
    """
    Signal-aware advanced routing.
    Returns the shortest path + alternative paths with signal strength data along the route.
    """
    try:
        result = _find_route_path(lat, lng, dest_lat, dest_lng, acceptable_range)
        
        # Add signal-aware alternatives: generate a few perturbed paths
        alternatives = _generate_alternative_paths(lat, lng, dest_lat, dest_lng, acceptable_range)
        result["alternatives"] = alternatives
        
        return result
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Route computation failed: {str(e)}")


def _generate_alternative_paths(lat: float, lng: float, dest_lat: float, dest_lng: float, acceptable_range: int = 500) -> list[dict]:
    """Generate alternative routes by using different waypoints."""
    graph = _load_light_route_graph()
    nodes = graph["nodes"]
    edges = graph["edges"]

    adj: dict[str, list[tuple[str, float]]] = {}
    for u, v, length in edges:
        adj.setdefault(u, []).append((v, length))
        adj.setdefault(v, []).append((u, length))

    def nearest_node(lat: float, lng: float) -> str | None:
        best_id = None
        best_dist = float("inf")
        for nid, ndata in nodes.items():
            d = _haversine_distance(lat, lng, ndata["lat"], ndata["lng"])
            if d < best_dist:
                best_dist = d
                best_id = nid
        return best_id

    start_node = nearest_node(lat, lng)
    dest_node = nearest_node(dest_lat, dest_lng)
    if start_node is None or dest_node is None:
        return []

    def dijkstra_to_all(from_node: str) -> tuple[dict[str, float], dict[str, str | None]]:
        dists: dict[str, float] = {from_node: 0}
        prevs: dict[str, str | None] = {from_node: None}
        pq: list[tuple[float, str]] = [(0, from_node)]
        while pq:
            d, u = heapq.heappop(pq)
            if d > dists.get(u, float("inf")):
                continue
            for v, w in adj.get(u, []):
                nd = d + w
                if nd < dists.get(v, float("inf")):
                    dists[v] = nd
                    prevs[v] = u
                    heapq.heappush(pq, (nd, v))
        return dists, prevs

    def reconstruct_path(prevs: dict, target: str) -> list[dict]:
        path_nodes: list[str] = []
        u: str | None = target
        while u is not None:
            path_nodes.append(u)
            u = prevs.get(u)
        path_nodes.reverse()
        return [{"lat": nodes[nid]["lat"], "lng": nodes[nid]["lng"]} for nid in path_nodes]

    # Forward distances from start
    dists_from_start, _ = dijkstra_to_all(start_node)
    # Backward distances to dest
    dists_to_dest, prevs_to_dest = dijkstra_to_all(dest_node)

    if dest_node not in dists_from_start:
        return []

    shortest_dist = dists_from_start[dest_node]

    # Find intermediate nodes that are "reasonable" deviations
    alternatives = []
    # Pick 2-3 candidate waypoints that are within 30-60% along the path
    candidates = []
    for nid, ndata in nodes.items():
        if nid == start_node or nid == dest_node:
            continue
        if nid not in dists_from_start or nid not in dists_to_dest:
            continue
        via_dist = dists_from_start[nid] + dists_to_dest[nid]
        # Only consider routes that are at most 1.5x the shortest path
        if via_dist <= shortest_dist * 1.5 and via_dist > shortest_dist * 1.05:
            candidates.append((nid, via_dist))

    # Sort by distance (closest to shortest first)
    candidates.sort(key=lambda x: x[1])
    
    # Take 2-3 best candidates, ensuring diversity (different branches)
    used_paths: set[str] = set()
    for nid, _ in candidates[:5]:
        if len(alternatives) >= 3:
            break
        path = reconstruct_path(prevs_to_dest, nid)
        path_key = str([(p["lat"], p["lng"]) for p in path[:3]])
        if path_key in used_paths:
            continue
        used_paths.add(path_key)
        
        alt_distance = dists_from_start.get(nid, 0) + dists_to_dest.get(nid, 0)
        if alt_distance > 0:
            alternatives.append({
                "path": path,
                "distance": round(alt_distance, 1),
            })

    return alternatives


@app.post("/foto2ap/recognize")
async def foto2ap_recognize(file: UploadFile = File(...)):
    """
    Upload a photo of an AP access point and recognise its name + location.

    Uses PaddleOCR to extract text from the image, parses the AP code,
    and looks up its coordinates in the GeoJSON database.

    Returns:
        {
            "success": true,
            "ap_name": "AP-ETSE58",
            "lat": 41.5004,
            "lng": 2.1129,
            "building": "ETSE",
            "floor": 0,
            "espacio": "..."
        }
    """
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="File must be an image")

    try:
        image_bytes = await file.read()
        if len(image_bytes) == 0:
            raise HTTPException(status_code=400, detail="Empty file")
    except Exception:
        raise HTTPException(status_code=400, detail="Failed to read uploaded file")

    try:
        from foto2ap_service import recognize_ap
        result = recognize_ap(image_bytes)
    except ImportError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"OCR recognition failed: {str(e)}")

    if result is None:
        return JSONResponse(
            status_code=404,
            content={"success": False, "message": "No AP could be recognised in the image. Try a clearer photo of the AP label."}
        )

    return {"success": True, **result}


# --- Booking API endpoints ---


class BookingCreateRequest(BaseModel):
    teacher_id: Optional[str] = Field(default=None, max_length=100)
    room_code: Optional[str] = Field(default=None, max_length=50)
    date: str = Field(description="Date in YYYY-MM-DD format")
    start_hour: int = Field(ge=7, le=22)
    end_hour: int = Field(ge=8, le=23)
    n_students: int = Field(ge=1, le=200)
    min_performance: str = Field(default="Fair", pattern="^(Poor|Fair|Good|Excellent|Excellent\\+|Excellent\\+\\+)$")


class BookingCancelRequest(BaseModel):
    booking_id: str = Field(min_length=1)


class BookingPredictRequest(BaseModel):
    room_code: Optional[str] = Field(default=None, max_length=50)
    date: str = Field(description="Date in YYYY-MM-DD format")
    start_hour: int = Field(ge=7, le=22)
    end_hour: int = Field(ge=8, le=23)
    n_students: int = Field(ge=1, le=200)


class BookingSuggestSlotRequest(BaseModel):
    room_code: Optional[str] = Field(default=None, max_length=50)
    date: str = Field(description="Date in YYYY-MM-DD format")
    duration_hours: int = Field(ge=1, le=6)
    n_students: int = Field(ge=1, le=200)


class BookingAlternativesRequest(BaseModel):
    room_code: Optional[str] = Field(default=None, max_length=50)
    date: str = Field(description="Date in YYYY-MM-DD format")
    start_hour: int = Field(ge=7, le=22)
    end_hour: int = Field(ge=8, le=23)
    n_students: int = Field(ge=1, le=200)
    min_performance: str = Field(default="Fair", pattern="^(Poor|Fair|Good|Excellent|Excellent\\+|Excellent\\+\\+)$")


@app.post("/booking/create")
async def booking_create(request: BookingCreateRequest):
    """Create a new booking after checking availability and predicting performance."""
    if request.end_hour <= request.start_hour:
        raise HTTPException(status_code=400, detail="End time must be after start time")

    if not request.room_code:
        return {"success": False, "message": "Room code is required", "booking": None}

    ap_info = _get_ap_from_room(request.room_code)
    if ap_info is None:
        raise HTTPException(status_code=404, detail=f"Room '{request.room_code}' not found")

    available, conflict = _check_booking_availability(
        _bookings, request.room_code, request.date,
        request.start_hour, request.end_hour
    )
    if not available:
        raise HTTPException(
            status_code=409,
            detail={
                "message": "Room already booked for this time slot",
                "conflict": {
                    "start_hour": conflict["start_hour"],
                    "end_hour": conflict["end_hour"],
                    "booking_id": conflict["booking_id"],
                }
            }
        )

    pred = _predict_booking_performance(
        request.room_code, request.date,
        request.start_hour, request.end_hour, request.n_students
    )

    booking = {
        "booking_id": str(uuid.uuid4())[:8].upper(),
        "teacher_id": request.teacher_id,
        "room_code": request.room_code.strip().upper(),
        "ap_name": ap_info["ap_name"],
        "date": request.date,
        "start_hour": request.start_hour,
        "end_hour": request.end_hour,
        "n_students": request.n_students,
        "min_performance": request.min_performance,
        "predicted_performance": pred.get("performance"),
        "warning": pred.get("warning"),
    }

    _bookings.append(booking)

    return {
        "success": True,
        "booking": booking,
        "prediction": {
            "performance": pred.get("performance"),
            "warning": pred.get("warning"),
            "model_source": pred.get("model_source"),
        }
    }


@app.post("/booking/predict")
async def booking_predict(request: BookingPredictRequest):
    """Predict performance for a room/time slot without creating a booking."""
    if request.end_hour <= request.start_hour:
        raise HTTPException(status_code=400, detail="End time must be after start time")

    if not request.room_code:
        return {"available": False, "prediction": {"performance": None, "warning": "Room code is required"}}

    ap_info = _get_ap_from_room(request.room_code)
    if ap_info is None:
        raise HTTPException(status_code=404, detail=f"Room '{request.room_code}' not found")

    available, conflict = _check_booking_availability(
        _bookings, request.room_code, request.date,
        request.start_hour, request.end_hour
    )

    pred = _predict_booking_performance(
        request.room_code, request.date,
        request.start_hour, request.end_hour, request.n_students
    )

    return {
        "room_code": request.room_code.strip().upper(),
        "ap_name": ap_info["ap_name"],
        "date": request.date,
        "start_hour": request.start_hour,
        "end_hour": request.end_hour,
        "n_students": request.n_students,
        "available": available,
        "conflict": {
            "start_hour": conflict["start_hour"] if conflict else None,
            "end_hour": conflict["end_hour"] if conflict else None,
            "booking_id": conflict["booking_id"] if conflict else None,
        } if conflict else None,
        "prediction": {
            "performance": pred.get("performance"),
            "warning": pred.get("warning"),
            "model_source": pred.get("model_source"),
        }
    }


@app.post("/booking/cancel")
async def booking_cancel(request: BookingCancelRequest):
    """Cancel an existing booking by its ID."""
    for i, book in enumerate(_bookings):
        if book["booking_id"] == request.booking_id:
            _bookings.pop(i)
            return {"success": True, "message": "Booking cancelled", "booking_id": request.booking_id}
    raise HTTPException(status_code=404, detail=f"Booking '{request.booking_id}' not found")


@app.get("/booking/list")
async def booking_list(teacher_id: Optional[str] = Query(default=None, description="Filter by teacher ID"),
                       room_code: Optional[str] = Query(default=None, description="Filter by room code"),
                       date: Optional[str] = Query(default=None, description="Filter by date (YYYY-MM-DD)")):
    """List bookings with optional filters."""
    results = _bookings
    if teacher_id:
        results = [b for b in results if b["teacher_id"] == teacher_id]
    if room_code:
        results = [b for b in results if b["room_code"] == room_code.strip().upper()]
    if date:
        results = [b for b in results if b["date"] == date]
    return {"bookings": results, "total": len(results)}


@app.post("/booking/suggest-slot")
async def booking_suggest_slot(request: BookingSuggestSlotRequest):
    """Suggest the best available time slot for a room and duration."""
    if not request.room_code:
        return {"found": False, "message": "Room code is required"}

    ap_info = _get_ap_from_room(request.room_code)
    if ap_info is None:
        raise HTTPException(status_code=404, detail=f"Room '{request.room_code}' not found")

    best = _suggest_best_slot(
        request.room_code, request.date,
        request.duration_hours, request.n_students
    )

    if best is None:
        return {
            "found": False,
            "message": "No available slots with prediction for this room and date"
        }

    return {"found": True, "slot": best}


@app.post("/booking/alternatives")
async def booking_alternatives(request: BookingAlternativesRequest):
    """Find alternative rooms on the same floor with better performance."""
    if request.end_hour <= request.start_hour:
        raise HTTPException(status_code=400, detail="End time must be after start time")

    if not request.room_code:
        return {"room_code": None, "alternatives": [], "total": 0}

    ap_info = _get_ap_from_room(request.room_code)
    if ap_info is None:
        raise HTTPException(status_code=404, detail=f"Room '{request.room_code}' not found")

    alternatives = _suggest_alternative_rooms(
        request.room_code, request.date,
        request.start_hour, request.end_hour,
        request.n_students, request.min_performance
    )

    return {
        "room_code": request.room_code.strip().upper(),
        "alternatives": alternatives,
        "total": len(alternatives)
    }


@app.get("/booking/room-info/{room_code:path}")
async def booking_room_info(room_code: str):
    """Get AP info for a room code."""
    ap_info = _get_ap_from_room(room_code)
    if ap_info is None:
        raise HTTPException(status_code=404, detail=f"Room '{room_code}' not found")
    return {
        "room_code": room_code.strip().upper(),
        "ap_name": ap_info["ap_name"],
        "building": ap_info["building"],
        "floor": ap_info["floor"],
    }


@app.get("/booking/availability/{room_code:path}/{date}")
async def booking_availability(room_code: str, date: str):
    """Get hourly availability for a room on a given date."""
    ap_info = _get_ap_from_room(room_code)
    if ap_info is None:
        raise HTTPException(status_code=404, detail=f"Room '{room_code}' not found")

    room_code_upper = room_code.strip().upper()
    booked_ranges = [
        (b["start_hour"], b["end_hour"])
        for b in _bookings
        if b["room_code"] == room_code_upper and b["date"] == date
    ]

    def is_booked(h):
        return any(s <= h < e for s, e in booked_ranges)

    hours = []
    for h in range(7, 22):
        hours.append({
            "hour": h,
            "available": not is_booked(h),
        })

    return {
        "room_code": room_code_upper,
        "ap_name": ap_info["ap_name"],
        "date": date,
        "hours": hours,
    }


@app.get("/cache/status")

async def cache_status():
    return {"strategy": "disk_based", "trend_file_ttl_seconds": TREND_FILE_TTL, "trend_files_count": len(list(TRENDS_DIR.glob("*.json"))) if TRENDS_DIR.exists() else 0, "models_loaded": {"decision_tree_v3": _decision_tree_v3 is not None, "building_encoder": _building_encoder is not None, "signal_strength_model": _signal_strength_model is not None}, "ap_index_size": len(_ap_index) if _ap_index else 0, "buildings_count": len(_buildings_list) if _buildings_list else 0}



def _precompute_all_trends():
    """Precompute trends for ALL APs at startup (background thread). Results go to disk, not RAM."""
    import pandas as pd
    try:
        model = _load_signal_strength_model()
    except Exception as e:
        print(f"[WARN] Cannot precompute trends: {e}")
        return
    ap_index = _build_ap_index()
    from datetime import datetime
    today = datetime.now()
    day_of_week = float(today.weekday())
    is_weekend = 1.0 if day_of_week >= 5 else 0.0
    day_of_month = float(today.day)
    month = float(today.month)
    
    TRENDS_DIR.mkdir(parents=True, exist_ok=True)
    
    written = 0
    for ap in ap_index:
        cache_key = ap["name"].strip().lower()
        trend_file = TRENDS_DIR / f"{cache_key}.json"
        if trend_file.exists():
            continue  # Already cached
        
        building_code = _encode_building(ap["building"])
        ap_name_code = _encode_ap_name(ap["name"])
        
        # Process one AP at a time to avoid huge DataFrame
        rows = []
        for hour in range(24):
            rows.append(_build_signal_features(
                building_code=building_code, floor=ap["floor"],
                hour=float(hour), day_of_week=day_of_week,
                is_weekend=is_weekend, day_of_month=day_of_month,
                month=month, ap_name_code=ap_name_code
            ))
        df = pd.DataFrame(rows)
        predictions = model.predict(df)
        smoothed_values = _smooth_series([float(p) for p in predictions], window=5)
        
        hourly_data = []
        signal_values = []
        for hour, signal_db in enumerate(smoothed_values):
            quality_info = _dbm_to_quality(signal_db)
            status = _dbm_to_status(signal_db)
            status_conf = _dbm_to_status_confidence(signal_db)
            hourly_data.append({
                "hour": hour,
                "signal_db": round(signal_db, 1),
                "signal_quality": quality_info["quality"],
                "bars": quality_info["bars"],
                "predicted_status": status,
                "status_confidence": status_conf,
            })
            signal_values.append(round(signal_db, 1))
        
        result = {
            "ap_name": ap["name"],
            "building": ap["building"],
            "floor": int(ap["floor"]),
            "lat": ap["lat"],
            "lng": ap["lng"],
            "trend": hourly_data,
            "day_type": "weekend" if is_weekend else "weekday",
            "day_name": DAY_NAMES[int(day_of_week)],
            "stats": {
                "avg_db": round(sum(smoothed_values) / len(smoothed_values), 1),
                "max_db": round(max(smoothed_values), 1),
                "min_db": round(min(smoothed_values), 1),
                "best_hour": smoothed_values.index(max(smoothed_values)),
                "worst_hour": smoothed_values.index(min(smoothed_values)),
            },
            "_cached_at": time.time(),
        }
        try:
            with open(trend_file, "w") as f:
                json.dump(result, f)
            written += 1
        except Exception:
            pass
    
    print(f"[INFO] Precomputed disk-cached trends for {written} APs ({len(ap_index) - written} already cached)")


@app.on_event("startup")
async def _startup_precompute():
    """Precompute trends on startup in background thread."""
    print("[INFO] Starting background trend precomputation...")
    import threading
    thread = threading.Thread(target=_precompute_all_trends, daemon=True)
    thread.start()


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False, log_level="info")
