# -*- coding: utf-8 -*-
"""Predictor2_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1755hyUBrCC0nlu2TarjTAnYnchNzW5Zi
"""

#Imports
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.kernel_approximation import Nystroem
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.model_selection import GridSearchCV
import ast
import os
import joblib

RANDOM_SEED = 0

"""#PRE"""

#Read "aps_processed.csv"
d_aps= pd.read_csv(
    "aps_processed.csv",
    engine="python",
    on_bad_lines="error"
)
#d_aps = pd.read_csv("aps_processed.csv")
d_aps.drop(columns = ["timestamp", "swarm_name", "firmware_version",	"macaddr", "date"], inplace=True)  #Drop timestamp because we have the info segmentated in 2 other columns and swarm_name because is not a feature that the predictor will use to predict

#When we use full dataset?
d_aps = d_aps.sample(n=1000, random_state=RANDOM_SEED)

#d_aps.head()
d_aps.info()

#Store the target class separately

#APs
y_status = d_aps["status"]
features_aps = d_aps.drop(columns = ["status"], inplace=False)
print(features_aps.info())
# 1. Separate radios column
radios_col = features_aps["radios"].copy()
print(radios_col.info())
# 2. If rows are strings, convert them into Python objects
radios_col = radios_col.apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

# 3. Expand each list of dictionaries into separate rows
radios_df = radios_col.explode()
print(radios_df.info())

# 4. Drop missing or invalid radio entries before normalization
radios_df = radios_df.dropna()

# 5. Convert dictionaries into dataframe columns
radios_df = pd.json_normalize(radios_df)

radios_df.head()
#print(radios_df.nunique())

#Remove radis comulmn from the dataset
d_aps_wr = features_aps.drop(columns = ["radios"], inplace=True)
#Separating a test set

#APs
X_test_ap = features_aps.sample(frac=0.1, replace=False, random_state=RANDOM_SEED, axis=None, ignore_index=False)

y_true_status = y_status.sample(frac=0.1, replace=False, random_state=RANDOM_SEED, axis=None, ignore_index=False) #Use RANDOM_SEED to sample the same rows from x and y

#Remove the test samples from the original set
index_to_remove = y_true_status.index
features_aps.drop(index_to_remove, inplace=True)
y_status.drop(index_to_remove, inplace=True)

#AP status
X_train_ap, X_val_ap, y_train_ap, y_val_ap = train_test_split(features_aps, y_status, test_size=0.33, random_state=RANDOM_SEED)

acc = (y_train_ap == "Up").sum() / len(y_train_ap)
print(acc)

"""#Classification"""

#We create a dictionary so comparing them is easier
dic_alg_cls_ap = {}

#Logistic Regression

#X_train_ap = pd.get_dummies(X_train_ap)
log_clf = LogisticRegression(penalty="l2", dual=False, class_weight='balanced', random_state=RANDOM_SEED).fit(X_train_ap, y_train_ap)

#Accuracy
accuracy=log_clf.score(X_val_ap, y_val_ap)

#F1-score
f1 = f1_score(y_val_ap, log_clf.predict(X_val_ap), average='weighted')


dic_alg_cls_ap["Logistic Regression"] = {"Call": "log_clf", "Accuracy":accuracy, "F1":f1}

'''NAIVE BAYES CLASSIFIER'''

gnb = GaussianNB()
gnb.fit(X_train_ap, y_train_ap)
y_pred = gnb.predict(X_val_ap)

#Accuracy
accuracy = gnb.score(X_val_ap, y_val_ap)

#F1-score
f1 = f1_score(y_val_ap, gnb.predict(X_val_ap), average='weighted')

dic_alg_cls_ap["Naïve Bayes"] = {"Call":"gnb", "Accuracy":accuracy, "F1":f1}

'''K-neighbours'''

n = [i for i in range(1, 26)]
accuracy = {}
for i in n:
  neigh = KNeighborsClassifier(n_neighbors=i)
  neigh.fit(X_train_ap, y_train_ap)

  accuracy[i] = neigh.score(X_val_ap, y_val_ap)

#Plot for choosing the best k
plt.plot(n, accuracy.values())
plt.title("k neighbors Vs Accuracy")
plt.xlabel("# Neighbors")
plt.ylabel("Accuracy")
plot_dir = "results"
os.makedirs(plot_dir, exist_ok=True)
plt.savefig(os.path.join(plot_dir, "knn_accuracy.png"), dpi=150, bbox_inches='tight')
plt.close()

neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(X_train_ap, y_train_ap)

#Accuracy
accuracy = neigh.score(X_val_ap, y_val_ap)
#F1-score
f1 = f1_score(y_val_ap, neigh.predict(X_val_ap), average='weighted')

dic_alg_cls_ap["5-Neighbors"] = {"Call":"neigh", "Accuracy":accuracy, "F1":f1}

'''SVM Linear - Direct (without Nystroem)'''

# Try different Cs to find the best one
Cs = [0.001, 0.01, 0.1, 0.5, 1, 2, 3, 10]
scores = {}
print("-----------FINDING BEST C (Linear SVM)-----------")
print("Cs to try:", Cs)

for c in Cs:
  print("====================================")
  # Define the classifier without kernel approximation
  svm_clf_linear = LinearSVC(C=c, max_iter=1000000, random_state=RANDOM_SEED, dual=False)
  svm_clf_linear.fit(X_train_ap, y_train_ap)
  score = svm_clf_linear.score(X_val_ap, y_val_ap)
  scores[score] = c
  print("C =", c)
  print("  --> Score: ", f"{score:.3f}")

print("====================================\n====================================")
# Train a classifier with the best parameter
best_c = scores[max(scores.keys())]
print("BEST C: " + str(best_c))

# Final classifier with best C
svm_clf_linear = LinearSVC(C=best_c, max_iter=1000000, random_state=RANDOM_SEED, dual=False)
svm_clf_linear.fit(X_train_ap, y_train_ap)

# Accuracy
accuracy = svm_clf_linear.score(X_val_ap, y_val_ap)

# F1-score
f1 = f1_score(y_val_ap, svm_clf_linear.predict(X_val_ap), average='weighted')

dic_alg_cls_ap["SVC linear"] = {"Call":"svm_clf_linear", "Accuracy":accuracy, "F1":f1}

# No pipeline needed since we're not using Nystroem
pipeline_svm_linear = svm_clf_linear

'''SVM RBF - Using native RBF kernel'''

# Try different gammas with native RBF kernel via SVC
gammas = [0.001, 0.01, 0.1, 0.5, 1]
scores = {}

print("-----------FINDING BEST GAMMA (RBF SVM)-----------")
print("Gammas to try:", gammas)

from sklearn.svm import SVC

for g in gammas:
  print("====================================")
  svm_clf_rbf = SVC(kernel='rbf', gamma=g, C=1.0, random_state=RANDOM_SEED)
  svm_clf_rbf.fit(X_train_ap, y_train_ap)
  score = svm_clf_rbf.score(X_val_ap, y_val_ap)
  scores[score] = g
  print("Gamma =", g)
  print("  --> Score: ", f"{score:.3f}")

print("====================================\n====================================")
# Train a classifier with the best parameters

best_gamma = scores[max(scores.keys())]
print("BEST GAMMA: " + str(best_gamma))

svm_clf_rbf = SVC(kernel='rbf', gamma=best_gamma, C=1.0, random_state=RANDOM_SEED)
svm_clf_rbf.fit(X_train_ap, y_train_ap)

# Accuracy
accuracy = svm_clf_rbf.score(X_val_ap, y_val_ap)

# F1-score
f1 = f1_score(y_val_ap, svm_clf_rbf.predict(X_val_ap), average='weighted')

dic_alg_cls_ap["SVC rbf"] = {"Call":"svm_clf_rbf", "Accuracy":accuracy, "F1":f1}

pipeline_svm_rbf = svm_clf_rbf

'''Decision Trees'''

#Try with different depths to find the best one for our algorithm. Chose according to the accuracy
possible_depths = [i for i in range(1, 50, 2)]
for depth in possible_depths:
  stellar_tree = DecisionTreeClassifier(criterion = "entropy", max_depth=depth, random_state = RANDOM_SEED).fit(X_train_ap, y_train_ap)
  print("Accuracy_"+str(depth)+": "+str(accuracy_score(y_val_ap, stellar_tree.predict(X_val_ap))))

x = max(possible_depths)
#Best depth
stellar_tree = DecisionTreeClassifier(criterion = "entropy", max_depth= x , random_state = RANDOM_SEED).fit(X_train_ap, y_train_ap)

#Accuracy
accuracy = accuracy_score(y_val_ap, stellar_tree.predict(X_val_ap))

#F1-score
f1 = f1_score(y_val_ap, stellar_tree.predict(X_val_ap), average='weighted')

dic_alg_cls_ap["Decision Tree"] = {"Call":"stellar_tree", "Accuracy":accuracy, "F1":f1}

from sklearn import tree
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))

tree.plot_tree(
    stellar_tree,
    feature_names=X_train_ap.columns,  # Uses your dataframe column names
    class_names=["Up", "Down"],  # optional
    filled=True,
    rounded=True
)

plot_dir = "results"
os.makedirs(plot_dir, exist_ok=True)
plt.savefig(os.path.join(plot_dir, "decision_tree.png"), dpi=150, bbox_inches='tight')
plt.close()

'''Grid Search'''
# Find the best combination of parameters
params = {'max_leaf_nodes': list(range(2, 100)), 'min_samples_split': [2, 3, 4, 5]}

#Train the model with the best parameters
grid_stellar = GridSearchCV(DecisionTreeClassifier(random_state=RANDOM_SEED), params, verbose=1, cv=5).fit(X_train_ap, y_train_ap)
best_tree_stellar = grid_stellar.best_estimator_

def tree_info(tree_):
    """Print brief insights of the tree."""
    print("depth:", tree_.get_depth(), ", n_leaves:", tree_.get_n_leaves())

tree_info(best_tree_stellar)

#Accuracy
accuracy = accuracy_score(y_val_ap, best_tree_stellar.predict(X_val_ap))

#F1-score
f1 = f1_score(y_val_ap, best_tree_stellar.predict(X_val_ap), average='weighted')

dic_alg_cls_ap["Decision Tree Grid (depth=2, leaves 3)"] = {"Call":"best_tree_stellar", "Accuracy":accuracy, "F1":f1}

def models_to_dataframe(models):
    """
    Function to create a dataframe based on the dictoary models.
    """
    # Build DataFrame
    df = pd.DataFrame([
        [k, round(m["Accuracy"], 3), round(m["F1"], 3)]
        for k, m in models.items()
    ], columns=["Model", "Accuracy", "F1"])

    # Set index and sort by Accuracy descending
    df = df.set_index("Model").sort_values(by="Accuracy", ascending=False)

    return df

results_df = models_to_dataframe(dic_alg_cls_ap)
print(results_df)

output_dir = "results"
os.makedirs(output_dir, exist_ok=True)
results_path = os.path.join(output_dir, "classification_results.csv")
results_df.to_csv(results_path)
print(f"Saved model results to {results_path}")

model_dir = "models"
os.makedirs(model_dir, exist_ok=True)

# Remove old model files so only the best model remains
for filename in os.listdir(model_dir):
    file_path = os.path.join(model_dir, filename)
    if os.path.isfile(file_path):
        os.remove(file_path)

model_objects = {
    "Logistic Regression": log_clf,
    "Naïve Bayes": gnb,
    "5-Neighbors": neigh,
    "SVC linear": pipeline_svm_linear,
    "SVC rbf": pipeline_svm_rbf,
    "Decision Tree": stellar_tree,
    "Decision Tree Grid (depth=2, leaves 3)": best_tree_stellar,
}

best_model_name = results_df.index[0]
best_model = model_objects.get(best_model_name)

if best_model is not None:
    safe_name = best_model_name.lower().replace(" ", "_").replace("(", "").replace(")", "").replace(",", "").replace("/", "_")
    model_path = os.path.join(model_dir, f"{safe_name}.joblib")
    joblib.dump(best_model, model_path)
    print(f"Saved best model object '{best_model_name}' to {model_path}")
else:
    print(f"Warning: no model object mapped for best model '{best_model_name}'")